# Generated by Django 4.0.6 on 2025-09-23 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('short_desc', models.TextField(blank=True)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated, e.g. Single-player, Prototype', max_length=160)),
                ('thumbnail', models.ImageField(upload_to='thumbs/')),
                ('build_folder', models.CharField(help_text="Folder under unity_build/ that contains index.html (e.g. 'sky_runner')", max_length=120)),
                ('published', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
