# Generated by Django 4.0.6 on 2025-09-24 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='build_zip',
            field=models.FileField(blank=True, null=True, upload_to='build_zips/'),
        ),
        migrations.AlterField(
            model_name='game',
            name='build_folder',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='game',
            name='tags',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AlterField(
            model_name='game',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbs/'),
        ),
    ]
