# Generated by Django 4.0.6 on 2025-09-24 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_game_build_zip_alter_game_build_folder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='build_folder',
            field=models.CharField(blank=True, help_text='Folder under media/unity_build/ that contains index.html', max_length=120),
        ),
    ]
