# Generated by Django 4.0.6 on 2025-09-27 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_alter_game_build_folder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='build_folder',
        ),
        migrations.RemoveField(
            model_name='game',
            name='build_zip',
        ),
        migrations.AddField(
            model_name='game',
            name='mac_zip',
            field=models.FileField(blank=True, null=True, upload_to='build_zips/mac/'),
        ),
        migrations.AddField(
            model_name='game',
            name='windows_zip',
            field=models.FileField(blank=True, null=True, upload_to='build_zips/windows/'),
        ),
    ]
