# Generated by Django 4.0.6 on 2025-10-01 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_remove_game_build_folder_remove_game_build_zip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='external_download_url',
            field=models.URLField(blank=True, help_text='itch.io or other download page', null=True),
        ),
    ]
