# Generated by Django 4.0.6 on 2025-10-01 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_game_external_download_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='external_download_url',
            field=models.URLField(blank=True, help_text='itch.io (or other) download page URL', null=True),
        ),
    ]
