# Generated by Django 5.2.7 on 2025-10-18 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0006_alter_game_external_download_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="web_zip",
            field=models.FileField(
                blank=True,
                help_text="Upload a Unity WebGL .zip (index.html + Build/, TemplateData/). It will be extracted to /media/web_builds/<slug>/.",
                null=True,
                upload_to="web_zips/",
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="external_download_url",
            field=models.URLField(
                blank=True,
                help_text="Play URL (will auto-fill after a successful WebGL zip upload)",
                null=True,
            ),
        ),
    ]
